### ISSUE TITLE
TourItems.xml

### ISSUE THREAD

**Issue by rxnnxs** [Marty651/DW2-Deutsch#5]
[TourItems.txt](https://github.com/Marty651/DW2-Deutsch/files/11584437/TourItems.txt)
Du musst es in .xml ändern.
Hier geht es was ich schon im Pull request "versucht" habe.
Da habe ich die Zeile nicht richtig getroffen, und hier darf ich keine XML hochladen.

Hier kannst Du es gut sehen was ich meine und wo das Problem lieght. Rest wird auch im Discord erklärt genauso wie im Pull Request,

**Comment by Marty651** [comment]
Soweit ich das sehe konnte ich deinen Pull-Request annehmen. Er hat das Update im Ordner 1.1.2.4/DW2 gemacht (nicht in 1.1.4.4/DW2). Ich denke, da hattest du es auch in deinem Fork verändert, richtig?

**Comment by rxnnxs** [comment]
Ja, denn es gab nicht alle Dateien im 1.1.4.4 Ordner. Nur die aktualisierten.

**Comment by Marty651** [comment]
Weitere Änderungswünsche:
1. "Konstruktion" statt "Bau"
2. Automatischer Start der Basic Tour bei neuem Spieler

**Comment by rxnnxs** [comment]
Ok, das ist abgehakt
